In [3]:
pip install wooldridge shap

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 12.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 547.9/547.9 kB 18.9 MB/s eta 0:00:00


In [49]:
from sklearn.experimental import enable_halving_search_cv
import pandas as pd
import scipy
import matplotlib.pyplot as plt
import numpy as np

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

from sklearn.pipeline import make_pipeline

from sklearn.model_selection import train_test_split
from sklearn.model_selection import learning_curve
from sklearn.model_selection import validation_curve

from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import HalvingRandomSearchCV
from sklearn.model_selection import RandomizedSearchCV


In [21]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from matplotlib.colors import ListedColormap

from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier

In [32]:
train = pd.read_csv('/content/data_inlf_train.csv')

In [23]:
test = pd.read_csv('/content/data_inlf_test.csv')

In [33]:
y = train['inlf']
x = train.drop (columns='inlf')

In [34]:
x.shape

(564, 8)

In [35]:
y.shape

(564,)

In [36]:
sc = StandardScaler()
sc.fit(x)
X_train_std = sc.transform(x)
X_test_std = sc.transform(test)

In [37]:
lr = LogisticRegression(C=100, solver='lbfgs', multi_class='ovr')
lr.fit(X_train_std, y)

LogisticRegression(C=100, multi_class='ovr')

In [69]:
y_pred = lr.predict(X_test_std)

In [70]:
lr.predict(X_test_std)

array([0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0])

In [71]:
luna = pd.DataFrame(data= y_pred, columns = ['Expected']). reset_index().rename(columns = {'index': 'id'})

In [72]:
luna. to_csv ('clasificación2.csv', index =False)

## param range

In [50]:
pipe_svc = make_pipeline(StandardScaler(), SVC(random_state=1))

In [53]:
param_range = [0.0001, 0.001, 0.01, 0.1,
      1.0, 10.0, 100.0, 1000.0]

In [55]:
param_grid = [{'svc__C': param_range,
      'svc__kernel': ['linear']},
      {'svc__C': param_range,
      'svc__gamma': param_range,
      'svc__kernel': ['rbf']}]

In [56]:
hs = HalvingRandomSearchCV(pipe_svc,
    param_distributions=param_grid,
    n_candidates='exhaust',
    resource='n_samples',
    factor=1.5,
    random_state=1,
    n_jobs=-1)

In [57]:
hs.fit(x,y)

HalvingRandomSearchCV(estimator=Pipeline(steps=[('standardscaler',
                                                 StandardScaler()),
                                                ('svc', SVC(random_state=1))]),
                      factor=1.5, n_jobs=-1,
                      param_distributions=[{'svc__C': [0.0001, 0.001, 0.01, 0.1,
                                                       1.0, 10.0, 100.0,
                                                       1000.0],
                                            'svc__kernel': ['linear']},
                                           {'svc__C': [0.0001, 0.001, 0.01, 0.1,
                                                       1.0, 10.0, 100.0,
                                                       1000.0],
                                            'svc__gamma': [0.0001, 0.001, 0.01,
                                                           0.1, 1.0, 10.0,
                                                           100.0, 1000.0],
                                            'svc__kernel': ['rbf']}],
                      random_state=1)

In [58]:
hs.predict(test)

array([1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0])

In [59]:
y_pred = hs.predict(test)

In [60]:
luna = pd.DataFrame(data= y_pred, columns = ['Expected']). reset_index().rename(columns = {'index': 'id'})

In [61]:
luna. to_csv ('clasificación2.csv', index =False)

In [62]:
param_range = [0.0001, 0.001, 0.01, 0.1, 1.0, 10.0, 100.0, 1000.0]

In [63]:
param_range = scipy.stats.loguniform(0.0001, 1000.0)

In [64]:
np.random.seed(1)
param_range.rvs(10)

array([8.30145146e-02, 1.10222804e+01, 1.00184520e-04, 1.30715777e-02,
       1.06485687e-03, 4.42965766e-04, 2.01289666e-03, 2.62376594e-02,
       5.98924832e-02, 5.91176467e-01])

In [65]:
pipe_svc = make_pipeline(StandardScaler(), SVC(random_state=1))


In [66]:
param_grid = [{'svc__C': param_range,
      'svc__kernel': ['linear']},
      {'svc__C': param_range,
      'svc__gamma': param_range,
      'svc__kernel': ['rbf']}]
rs = RandomizedSearchCV(estimator=pipe_svc,
      param_distributions=param_grid,
      scoring='accuracy',
      refit=True,
      n_iter=20,
      cv=10,
      random_state=1,
      n_jobs=-1)
rs = rs.fit(X_train, y_train)
print(rs.best_score_)

print(rs.best_params_)

0.9800000000000001
{'svc__C': 10.275278736640145, 'svc__gamma': 41.62004328670892, 'svc__kernel': 'rbf'}


In [67]:
rs.fit(x,y)

RandomizedSearchCV(cv=10,
                   estimator=Pipeline(steps=[('standardscaler',
                                              StandardScaler()),
                                             ('svc', SVC(random_state=1))]),
                   n_iter=20, n_jobs=-1,
                   param_distributions=[{'svc__C': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x78e8fcbabaf0>,
                                         'svc__kernel': ['linear']},
                                        {'svc__C': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x78e8fcbabaf0>,
                                         'svc__gamma': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x78e8fcbabaf0>,
                                         'svc__kernel': ['rbf']}],
                   random_state=1, scoring='accuracy')

In [68]:
rs.predict(test)

array([1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0])

In [73]:
y_pred = rs.predict(test)

In [74]:
luna = pd.DataFrame(data= y_pred, columns = ['Expected']). reset_index().rename(columns = {'index': 'id'})

In [75]:
luna. to_csv ('clasificación2.csv', index =False)

KNN

In [76]:
knn = KNeighborsClassifier(n_neighbors=5, p=2,
                          metric='minkowski')
knn.fit(X_train_std, y)

KNeighborsClassifier()

In [78]:
y_pred = knn.predict(test)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(


In [79]:
luna = pd.DataFrame(data= y_pred, columns = ['Expected']). reset_index().rename(columns = {'index': 'id'})

In [80]:
luna. to_csv ('clasificación2.csv', index =False)

In [82]:
pipe_svc = make_pipeline(StandardScaler(), KNeighborsClassifier())

In [88]:
param_grid = {'kneighborsclassifier__n_neighbors': [2,3,4,5,6,7,8,9,10],
             "kneighborsclassifier__metric":["euclidean","manhattan","minkowski"] }
rs = RandomizedSearchCV(estimator=pipe_svc,
      param_distributions=param_grid,
      scoring='accuracy',
      refit=True,
      n_iter=20,
      cv=10,
      random_state=1,
      n_jobs=-1)

In [89]:
rs.fit(x,y)

RandomizedSearchCV(cv=10,
                   estimator=Pipeline(steps=[('standardscaler',
                                              StandardScaler()),
                                             ('kneighborsclassifier',
                                              KNeighborsClassifier())]),
                   n_iter=20, n_jobs=-1,
                   param_distributions={'kneighborsclassifier__metric': ['euclidean',
                                                                         'manhattan',
                                                                         'minkowski'],
                                        'kneighborsclassifier__n_neighbors': [2,
                                                                              3,
                                                                              4,
                                                                              5,
                                                                              6,
                                                                              7,
                                                                              8,
                                                                              9,
                                                                              10]},
                   random_state=1, scoring='accuracy')

In [90]:
y_pred = rs.predict(test)

In [91]:
luna = pd.DataFrame(data= y_pred, columns = ['Expected']). reset_index().rename(columns = {'index': 'id'})

In [92]:
luna. to_csv ('clasificación2.csv', index =False)